# This is a basic workflow to help you get started with Actions

name: Code Mirror
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  schedule:
    # 每天北京时间9点跑
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '*/60 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Sync FederatedAI to Gitee
        uses: zengjice/hub-mirror-action@master
        with:
          # Gitee对应的秘钥
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PRIVATE_TOKEN }}
          # 需要同步的Github组织名（源）
          github_org: FederatedAI
          # 需要同步到的Gitee的组织名（目的）
          gitee_org: FederatedAI
          force_update: true
          clone_style: "ssh"
